import { useEffect, useState } from 'react';
import {
  X, BarChart3, Download, FileText, TrendingUp, Award, BookOpen,
  Calendar, Hash, Target, Layers, ChevronDown, ChevronUp, Info,
  Lock, CheckCircle2
} from 'lucide-react';
import { Article } from '../../data/mockData';
import { toast } from 'sonner';
import { useAuth } from '../../context/AuthContext';
import {
  getAnalysis,
  isLecturerPayload,
  StudentAnalysisReceipt,
  LecturerAnalysisPayload,
} from '../../services/analysisService';
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  PieChart, Pie, Cell, Legend, LineChart, Line, RadarChart, Radar, PolarGrid,
  PolarAngleAxis, PolarRadiusAxis
} from 'recharts';

/*
 * AnalysisResultsModal
 * -------------------------------------------------------------------------
 * Full-screen modal that shows the result of analyzing one or more papers.
 * Two completely different renders depending on who is logged in:
 *   - STUDENT  -> small "receipt" card only. No charts. Their analysis was
 *                 submitted for the lecturer to review.
 *   - LECTURER -> full dashboard: stat cards + 5 recharts charts + insights.
 * All the chart numbers are derived from the `articles` array passed in.
 */

interface AnalysisResultsModalProps {
  articles: Article[];                       // papers selected for this report
  depth: 'Fast' | 'Regular' | 'Deep';        // analysis mode (affects Depth metric)
  onClose: () => void;                        // close the modal
}

const EXPLANATION =
  'This analysis was generated by processing the full text, metadata, citations, methodology sections, and key findings of all selected papers. ' +
  'Statistical aggregations and pattern detection algorithms identified trends, gaps, and central themes across your research corpus.';

const COLORS = ['#dc2626', '#f59e0b', '#10b981', '#3b82f6', '#8b5cf6', '#ec4899'];

export default function AnalysisResultsModal({ articles, depth, onClose }: AnalysisResultsModalProps) {
  // Who is viewing? Lecturers see charts, students see a receipt.
  const { user } = useAuth();
  const role = user?.role === 'lecturer' ? 'lecturer' : 'student';
  // Stable id for this batch of articles (used to cache/fetch the analysis).
  const analysisId = `an-${articles.map(a => a.id).join('-').slice(0, 24)}`;

  // payload = server response. Shape differs by role (receipt vs full payload).
  const [payload, setPayload] = useState<StudentAnalysisReceipt | LecturerAnalysisPayload | null>(null);
  const [loading, setLoading] = useState(true);
  const [showExplanation, setShowExplanation] = useState(false);   // "How AI got this?" banner toggle
  const [activeSection, setActiveSection] = useState<number | null>(null); // which insight card is expanded

  // Fetch the analysis on mount / when the article set, role, or depth changes.
  // `cancelled` guards against setting state after the modal unmounts.
  useEffect(() => {
    let cancelled = false;
    getAnalysis(analysisId, role, articles, depth).then((p) => {
      if (!cancelled) { setPayload(p); setLoading(false); }
    });
    return () => { cancelled = true; };
  }, [analysisId, role, depth]);

  // ─── Student render (early return) ───
  // Students never see the charts. They get a small confirmation card showing
  // status + created time, telling them the data went to their lecturer.
  // Everything below this `if` block only runs for lecturers.
  if (role === 'student') {
    const receipt = payload && !isLecturerPayload(payload) ? payload : null;
    return (
      <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm z-50 flex items-center justify-center p-4">
        <div className="bg-card w-full max-w-md rounded-2xl shadow-2xl border border-border overflow-hidden">
          <div className="flex items-center justify-between px-5 py-4 border-b border-border">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 bg-muted rounded-xl flex items-center justify-center text-red-600">
                <Lock className="w-5 h-5" />
              </div>
              <div>
                <h2 className="font-bold text-foreground text-base">Analysis Ready</h2>
                <p className="text-xs text-muted-foreground">Submitted for lecturer review</p>
              </div>
            </div>
            <button
              onClick={onClose}
              className="p-2 text-muted-foreground hover:text-red-600 hover:bg-red-50 dark:hover:bg-red-950 rounded-lg transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          <div className="p-5 space-y-4">
            {loading || !receipt ? (
              <div className="text-sm text-muted-foreground">Generating analysisâ€¦</div>
            ) : (
              <>
                <div className="flex items-start gap-3 p-3 rounded-xl bg-amber-50 dark:bg-amber-950/40 border border-amber-200 dark:border-amber-800">
                  <CheckCircle2 className="w-5 h-5 text-amber-600 dark:text-amber-400 mt-0.5 shrink-0" />
                  <div className="text-xs text-amber-800 dark:text-amber-200">
                    Charts and detailed data are visible to your lecturer only. Continue practicing in the Research Chat.
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-3">
                  <div className="p-3 rounded-xl bg-muted border border-border">
                    <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-wide mb-1">Status</p>
                    <p className="text-sm font-bold text-foreground capitalize">{receipt.status}</p>
                  </div>
                  <div className="p-3 rounded-xl bg-muted border border-border">
                    <p className="text-[10px] font-bold text-muted-foreground uppercase tracking-wide mb-1">Created</p>
                    <p className="text-sm font-bold text-foreground">{new Date(receipt.createdAt).toLocaleString()}</p>
                  </div>
                </div>

                <button
                  onClick={onClose}
                  className="w-full py-3 bg-red-600 hover:bg-red-700 text-white rounded-xl text-sm font-bold transition-colors"
                >
                  Got it
                </button>
              </>
            )}
          </div>
        </div>
      </div>
    );
  }

  // Lecturer view continues below with full charts.

  /* ─── Calculate Statistics ───
   * Everything below is derived synchronously from the `articles` prop.
   * No API call: the charts are computed client-side from paper metadata. */
  const totalCitations = articles.reduce((sum, a) => sum + a.citations, 0); // sum of all citations
  const avgCitations = Math.round(totalCitations / articles.length);        // mean per paper
  const totalArticles = articles.length;

  // Year distribution: count how many papers were published each year.
  // Shape: { 2021: 3, 2022: 5, ... } -> later turned into sorted chart rows.
  const yearCounts = articles.reduce((acc, a) => {
    acc[a.year] = (acc[a.year] || 0) + 1;
    return acc;
  }, {} as Record<number, number>);

  const yearData = Object.entries(yearCounts)
    .map(([year, count]) => ({ year: parseInt(year), count }))
    .sort((a, b) => a.year - b.year);

  // Topics frequency: tally every topic tag across all papers, keep the top 6.
  // Feeds the horizontal "Most Frequent Research Topics" bar chart.
  const topicCounts = articles.reduce((acc, a) => {
    a.topics.forEach(topic => {
      acc[topic] = (acc[topic] || 0) + 1;
    });
    return acc;
  }, {} as Record<string, number>);

  const topicData = Object.entries(topicCounts)
    .map(([topic, count]) => ({ topic, count }))
    .sort((a, b) => b.count - a.count)
    .slice(0, 6);

  // Methodology breakdown: bucket each paper's methodology string into one of
  // four coarse categories by keyword matching. Feeds the pie chart.
  const methodCounts = articles.reduce((acc, a) => {
    const method = a.methodology.includes('survey') || a.methodology.includes('literature')
      ? 'Literature Review'
      : a.methodology.includes('experimental') || a.methodology.includes('analysis')
      ? 'Experimental'
      : a.methodology.includes('quantitative')
      ? 'Quantitative'
      : 'Qualitative';
    acc[method] = (acc[method] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  const methodData = Object.entries(methodCounts).map(([name, value]) => ({ name, value }));

  // Citation distribution: one row per paper, sorted most-cited first.
  // Feeds the "Citation Distribution by Paper" vertical bar chart.
  const citationData = articles
    .map((a, idx) => ({
      name: `Paper ${idx + 1}`,
      citations: a.citations,
      title: a.title.substring(0, 30) + '...'
    }))
    .sort((a, b) => b.citations - a.citations);

  // Quality metrics: 5 synthetic 0-100 scores for the radar chart. Each is a
  // rough heuristic (impact, recency, topic coverage, chosen depth, plus a
  // randomized "consistency"). These are illustrative, not real measurements.
  const qualityMetrics = [
    {
      metric: 'Avg Impact',
      score: Math.min(100, avgCitations / 5)
    },
    {
      metric: 'Recency',
      score: Math.min(100, ((Math.max(...articles.map(a => a.year)) - 2020) / 6) * 100)
    },
    {
      metric: 'Coverage',
      score: Math.min(100, (Object.keys(topicCounts).length / 10) * 100)
    },
    {
      metric: 'Depth',
      score: depth === 'Deep' ? 95 : depth === 'Regular' ? 75 : 50
    },
    {
      metric: 'Consistency',
      score: 70 + Math.random() * 25
    }
  ];

  // Key insights: 4 human-readable summary blurbs built from the stats above
  // (publication trend, dominant topic, methodology mix, citation impact).
  // Rendered as collapsible cards at the bottom of the dashboard.
  const insights = [
    {
      title: 'Publication Trend',
      description: `${Math.round((yearData[yearData.length - 1]?.count || 0) / (yearData[0]?.count || 1) * 100)}% increase in publications over the analyzed period, indicating growing research interest.`
    },
    {
      title: 'Dominant Topics',
      description: `"${topicData[0]?.topic}" appears most frequently (${topicData[0]?.count}Ã— across papers), suggesting it's a central theme in your corpus.`
    },
    {
      title: 'Methodology Balance',
      description: `${methodData.length} distinct research methodologies identified. ${methodData[0]?.name} approach is most common (${Math.round((methodData[0]?.value / totalArticles) * 100)}%).`
    },
    {
      title: 'Citation Impact',
      description: `Average ${avgCitations} citations per paper. Top paper has ${Math.max(...articles.map(a => a.citations))} citations, ${Math.round((Math.max(...articles.map(a => a.citations)) / avgCitations - 1) * 100)}% above average.`
    }
  ];

  // Export is a stub: shows a toast only, no real file is generated yet.
  const handleExport = (format: 'pdf' | 'excel') => {
    toast.success(`Exporting analysis as ${format.toUpperCase()}â€¦`, {
      description: 'Your statistical report will be ready shortly.',
    });
  };

  // ─── Lecturer dashboard render ───
  // Layout: header (export + How AI) -> stat cards -> 2 chart rows ->
  // topic bar chart -> collapsible AI insight cards.
  return (
    <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm z-50 flex items-center justify-center p-2 md:p-6">
      <div className="bg-white w-full max-w-6xl max-h-[95vh] rounded-2xl shadow-2xl flex flex-col overflow-hidden border border-slate-200">

        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-border bg-card flex-shrink-0">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 bg-muted rounded-xl flex items-center justify-center text-red-600">
              <BarChart3 className="w-5 h-5" />
            </div>
            <div>
              <h2 className="font-bold text-slate-900 text-lg">Research Analysis</h2>
              <p className="text-xs text-slate-500">
                {totalArticles} papers â€¢ {depth} analysis mode â€¢ AI-generated insights
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => setShowExplanation(!showExplanation)}
              className="hidden sm:flex items-center gap-1.5 px-3 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-600 rounded-lg text-xs font-bold transition-colors border border-slate-200"
            >
              <Info className="w-3.5 h-3.5" />
              How AI got this?
            </button>
            <div className="relative group">
              <button className="flex items-center gap-1.5 px-3 py-1.5 bg-red-50 hover:bg-red-100 text-red-700 rounded-lg text-xs font-bold transition-colors border border-red-200">
                <Download className="w-3.5 h-3.5" />
                Export
              </button>
              <div className="absolute right-0 top-full mt-1 w-44 bg-white border border-slate-200 rounded-xl shadow-lg py-1 opacity-0 pointer-events-none group-hover:opacity-100 group-hover:pointer-events-auto transition-all z-30">
                <button
                  onClick={() => handleExport('pdf')}
                  className="w-full px-3 py-2 text-sm text-slate-700 hover:bg-red-50 hover:text-red-700 flex items-center gap-2 font-medium"
                >
                  <FileText className="w-4 h-4" /> Export to PDF
                </button>
                <button
                  onClick={() => handleExport('excel')}
                  className="w-full px-3 py-2 text-sm text-slate-700 hover:bg-red-50 hover:text-red-700 flex items-center gap-2 font-medium"
                >
                  <FileText className="w-4 h-4" /> Export to Excel
                </button>
              </div>
            </div>
            <button
              onClick={onClose}
              className="p-2 text-slate-400 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* AI Explanation banner */}
        {showExplanation && (
          <div className="mx-6 mt-4 bg-slate-100 dark:bg-slate-800 border border-slate-300 dark:border-slate-600 rounded-xl p-4 flex items-start gap-3 flex-shrink-0">
            <Info className="w-4 h-4 text-amber-600 mt-0.5 flex-shrink-0" />
            <div>
              <p className="text-xs font-bold text-amber-800 mb-1">How AI generated this analysis</p>
              <p className="text-xs text-amber-700 leading-relaxed">{EXPLANATION}</p>
            </div>
            <button onClick={() => setShowExplanation(false)} className="text-amber-400 hover:text-amber-600 ml-auto flex-shrink-0">
              <X className="w-4 h-4" />
            </button>
          </div>
        )}

        {/* Content */}
        <div className="flex-1 overflow-y-auto p-6 space-y-6">

          {/* â•â•â• Key Statistics Cards â•â•â• */}
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
            <div className="bg-gradient-to-br from-red-50 to-red-100 border-2 border-red-200 rounded-xl p-4">
              <div className="flex items-center justify-between mb-2">
                <FileText className="w-5 h-5 text-slate-600" />
                <span className="text-[10px] font-bold text-red-600 uppercase tracking-wider">Total</span>
              </div>
              <div className="text-3xl font-bold text-red-900 mb-1">{totalArticles}</div>
              <div className="text-xs font-medium text-red-700">Papers Analyzed</div>
            </div>

            <div className="bg-gradient-to-br from-amber-50 to-amber-100 border-2 border-amber-200 rounded-xl p-4">
              <div className="flex items-center justify-between mb-2">
                <BookOpen className="w-5 h-5 text-amber-600" />
                <span className="text-[10px] font-bold text-amber-600 uppercase tracking-wider">Average</span>
              </div>
              <div className="text-3xl font-bold text-amber-900 mb-1">{avgCitations}</div>
              <div className="text-xs font-medium text-amber-700">Citations/Paper</div>
            </div>

            <div className="bg-gradient-to-br from-blue-50 to-blue-100 border-2 border-blue-200 rounded-xl p-4">
              <div className="flex items-center justify-between mb-2">
                <Hash className="w-5 h-5 text-blue-600" />
                <span className="text-[10px] font-bold text-blue-600 uppercase tracking-wider">Total</span>
              </div>
              <div className="text-3xl font-bold text-blue-900 mb-1">{totalCitations}</div>
              <div className="text-xs font-medium text-blue-700">Citations Sum</div>
            </div>

            <div className="bg-gradient-to-br from-green-50 to-green-100 border-2 border-green-200 rounded-xl p-4">
              <div className="flex items-center justify-between mb-2">
                <Layers className="w-5 h-5 text-green-600" />
                <span className="text-[10px] font-bold text-green-600 uppercase tracking-wider">Topics</span>
              </div>
              <div className="text-3xl font-bold text-green-900 mb-1">{Object.keys(topicCounts).length}</div>
              <div className="text-xs font-medium text-green-700">Unique Topics</div>
            </div>
          </div>

          {/* â•â•â• Charts Row 1: Citation Distribution + Quality Radar â•â•â• */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Citation Distribution Bar Chart */}
            <div className="bg-white border border-slate-200 rounded-xl p-5">
              <h3 className="font-bold text-slate-800 text-sm mb-4 flex items-center gap-2">
                <Award className="w-4 h-4 text-red-600" />
                Citation Distribution by Paper
              </h3>
              <ResponsiveContainer width="100%" height={280}>
                <BarChart data={citationData} margin={{ top: 5, right: 5, left: -20, bottom: 5 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                  <XAxis dataKey="name" tick={{ fill: '#64748b', fontSize: 11, fontWeight: 600 }} />
                  <YAxis tick={{ fill: '#64748b', fontSize: 11 }} />
                  <Tooltip
                    contentStyle={{ backgroundColor: '#fff', border: '1px solid #e2e8f0', borderRadius: '8px', fontSize: '12px' }}
                    labelStyle={{ fontWeight: 'bold', color: '#1e293b' }}
                  />
                  <Bar dataKey="citations" fill="#dc2626" radius={[8, 8, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>

            {/* Quality Radar Chart */}
            <div className="bg-white border border-slate-200 rounded-xl p-5">
              <h3 className="font-bold text-slate-800 text-sm mb-4 flex items-center gap-2">
                <Target className="w-4 h-4 text-red-600" />
                Research Quality Metrics
              </h3>
              <ResponsiveContainer width="100%" height={280}>
                <RadarChart data={qualityMetrics}>
                  <PolarGrid stroke="#e2e8f0" />
                  <PolarAngleAxis dataKey="metric" tick={{ fill: '#64748b', fontSize: 11, fontWeight: 600 }} />
                  <PolarRadiusAxis angle={90} domain={[0, 100]} tick={{ fill: '#94a3b8', fontSize: 10 }} />
                  <Radar name="Quality" dataKey="score" stroke="#dc2626" fill="#dc2626" fillOpacity={0.3} strokeWidth={2} />
                  <Tooltip />
                </RadarChart>
              </ResponsiveContainer>
            </div>
          </div>

          {/* â•â•â• Charts Row 2: Year Trend + Methodology Breakdown â•â•â• */}
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            {/* Publication Year Trend */}
            <div className="bg-white border border-slate-200 rounded-xl p-5">
              <h3 className="font-bold text-slate-800 text-sm mb-4 flex items-center gap-2">
                <Calendar className="w-4 h-4 text-red-600" />
                Publication Timeline
              </h3>
              <ResponsiveContainer width="100%" height={280}>
                <LineChart data={yearData} margin={{ top: 5, right: 5, left: -20, bottom: 5 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                  <XAxis dataKey="year" tick={{ fill: '#64748b', fontSize: 11, fontWeight: 600 }} />
                  <YAxis tick={{ fill: '#64748b', fontSize: 11 }} />
                  <Tooltip
                    contentStyle={{ backgroundColor: '#fff', border: '1px solid #e2e8f0', borderRadius: '8px', fontSize: '12px' }}
                    labelStyle={{ fontWeight: 'bold', color: '#1e293b' }}
                  />
                  <Line type="monotone" dataKey="count" stroke="#dc2626" strokeWidth={3} dot={{ fill: '#dc2626', r: 5 }} />
                </LineChart>
              </ResponsiveContainer>
            </div>

            {/* Methodology Pie Chart */}
            <div className="bg-white border border-slate-200 rounded-xl p-5">
              <h3 className="font-bold text-slate-800 text-sm mb-4 flex items-center gap-2">
                <TrendingUp className="w-4 h-4 text-red-600" />
                Methodology Breakdown
              </h3>
              <ResponsiveContainer width="100%" height={280}>
                <PieChart>
                  <Pie
                    data={methodData}
                    cx="50%"
                    cy="50%"
                    labelLine={false}
                    label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}
                    outerRadius={90}
                    fill="#8884d8"
                    dataKey="value"
                  >
                    {methodData.map((_entry, index) => (
                      <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip />
                  <Legend wrapperStyle={{ fontSize: '12px', fontWeight: 600 }} />
                </PieChart>
              </ResponsiveContainer>
            </div>
          </div>

          {/* â•â•â• Topic Frequency Bar Chart â•â•â• */}
          <div className="bg-white border border-slate-200 rounded-xl p-5">
            <h3 className="font-bold text-slate-800 text-sm mb-4 flex items-center gap-2">
              <Hash className="w-4 h-4 text-red-600" />
              Most Frequent Research Topics
            </h3>
            <ResponsiveContainer width="100%" height={280}>
              <BarChart data={topicData} layout="vertical" margin={{ top: 5, right: 20, left: 5, bottom: 5 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" />
                <XAxis type="number" tick={{ fill: '#64748b', fontSize: 11 }} />
                <YAxis dataKey="topic" type="category" tick={{ fill: '#64748b', fontSize: 11, fontWeight: 600 }} width={120} />
                <Tooltip
                  contentStyle={{ backgroundColor: '#fff', border: '1px solid #e2e8f0', borderRadius: '8px', fontSize: '12px' }}
                />
                <Bar dataKey="count" fill="#3b82f6" radius={[0, 8, 8, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>

          {/* â•â•â• AI-Generated Insights â•â•â• */}
          <div className="bg-white border border-slate-200 rounded-xl p-5">
            <h3 className="font-bold text-slate-800 text-sm mb-3 flex items-center gap-2">
              <BarChart3 className="w-4 h-4 text-red-600" />
              AI-Generated Insights
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {insights.map((insight, idx) => (
                <div
                  key={idx}
                  className="bg-slate-50 border border-slate-200 rounded-xl overflow-hidden cursor-pointer hover:border-red-300 hover:shadow-sm transition-all"
                  onClick={() => setActiveSection(activeSection === idx ? null : idx)}
                >
                  <div className="flex items-center justify-between px-4 py-3">
                    <span className="font-bold text-slate-800 text-sm">{insight.title}</span>
                    {activeSection === idx
                      ? <ChevronUp className="w-4 h-4 text-slate-400" />
                      : <ChevronDown className="w-4 h-4 text-slate-400" />
                    }
                  </div>
                  {activeSection === idx && (
                    <div className="px-4 pb-4 border-t border-slate-100">
                      <p className="text-sm text-slate-600 leading-relaxed pt-3">{insight.description}</p>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}

