import { useState } from 'react';
import {
  X, GitCompare, Download, FileText, HelpCircle, Star,
  ChevronDown, ChevronUp, Info, Award, BookOpen, TrendingUp
} from 'lucide-react';
import { Article } from '../../data/mockData';
import { toast } from 'sonner';
import ArticleIcon from '../ui/ArticleIcon';
import { RadarChart, Radar, PolarGrid, PolarAngleAxis, PolarRadiusAxis, ResponsiveContainer, Legend } from 'recharts';

/*
 * ComparisonModal
 * -------------------------------------------------------------------------
 * The richer, modal version of the comparison view (opened from
 * AnalyzedReports). Adds visual scoring on top of the plain table:
 *   - a radar chart comparing papers across 4 dimensions
 *   - per-paper score cards (citations, impact, progress bars)
 *   - a "Best" badge on the most-cited paper
 *   - a field-by-field table + collapsible AI insight cards
 * Can also spin off a chat via the 'create-chat-from-comparison' event.
 * NOTE: scores are mock/random (see generateScores) — not real metrics.
 */

interface ComparisonModalProps {
  articles: Article[];   // papers to compare (up to ~4 look good)
  onClose: () => void;
}

const EXPLANATION =
  'This comparison was generated by analyzing each paper\'s abstract, methodology section, key findings, and citation patterns. ' +
  'The AI cross-referenced terminology, research objectives, and statistical outcomes to surface similarities and divergences.';

/* â”€â”€â”€ Paper quality scores (mock) â”€â”€â”€ */
interface PaperScores {
  reliability: number;
  readability: number;
  methodology: number;
  relevance: number;
  citations: number;
  impactFactor: number;
}

// Fabricate quality scores for a paper. Only `citations` is real; reliability
// is loosely tied to citations, the rest are random within plausible ranges.
// Used to fill the radar chart and the per-paper score cards.
const generateScores = (article: Article): PaperScores => ({
  reliability: Math.min(100, 65 + (article.citations / 100) * 35),
  readability: Math.floor(70 + Math.random() * 25),
  methodology: Math.floor(60 + Math.random() * 35),
  relevance: Math.floor(75 + Math.random() * 20),
  citations: article.citations,
  impactFactor: parseFloat((2.5 + Math.random() * 5).toFixed(1)),
});

const aiInsights = [
  {
    label: 'Common Themes',
    text: 'Both papers share a focus on algorithmic improvement and data-driven decision-making, with emphasis on practical real-world applications.',
  },
  {
    label: 'Methodological Divergence',
    text: 'The papers adopt distinct research designs â€” one relies on literature synthesis while the other employs empirical trials â€” leading to complementary rather than competing conclusions.',
  },
  {
    label: 'Conflicting Findings',
    text: 'Paper A reports a 23% improvement in throughput, whereas Paper B attributes a 37% efficiency gain to a different mechanism. Both claims may be valid given different evaluation contexts.',
  },
  {
    label: 'Recommendation',
    text: 'A follow-up synthesis study combining both methodologies could provide a more generalizable conclusion for the field.',
  },
];

const comparisonCategories = [
  { key: 'authors',      label: 'Authors' },
  { key: 'year',         label: 'Year' },
  { key: 'topics',       label: 'Topics / Keywords' },
  { key: 'methodology',  label: 'Methodology' },
  { key: 'keyFindings',  label: 'Key Findings' },
  { key: 'citations',    label: 'Citations' },
  { key: 'abstract',     label: 'Abstract' },
];

// Render one comparison-table cell, formatting by field type: keyFindings ->
// bulleted list, topics -> coloured pills, other arrays -> CSV, abstract ->
// paragraph, scalars -> plain text (em-dash when missing).
function renderCell(article: Article, key: string) {
  const value = article[key as keyof Article];
  if (key === 'keyFindings' && Array.isArray(value)) {
    return (
      <ul className="space-y-1 text-sm text-slate-700">
        {(value as string[]).map((item, idx) => (
          <li key={idx} className="flex items-start gap-2">
            <span className="w-1.5 h-1.5 bg-red-400 rounded-full mt-1.5 flex-shrink-0" />
            {item}
          </li>
        ))}
      </ul>
    );
  }
  if (key === 'topics' && Array.isArray(value)) {
    return (
      <div className="flex flex-wrap gap-1">
        {(value as string[]).map((t, i) => (
          <span key={i} className="px-2 py-0.5 bg-red-50 text-red-700 rounded text-xs font-medium border border-red-100">
            {t}
          </span>
        ))}
      </div>
    );
  }
  if (Array.isArray(value)) return (value as string[]).join(', ');
  if (key === 'abstract') {
    return <p className="text-sm text-slate-700 leading-relaxed" style={{ minHeight: 'auto' }}>{value as string}</p>;
  }
  return <span className="text-sm text-slate-700">{String(value ?? 'â€”')}</span>;
}

export default function ComparisonModal({ articles, onClose }: ComparisonModalProps) {
  const [showExplanation, setShowExplanation] = useState(false);          // "How AI got this?" banner
  const [activeInsight, setActiveInsight] = useState<number | null>(null); // expanded insight card
  // "Best" paper = highest citation count; gets the gold badge/border.
  const bestMatchIdx = articles.reduce(
    (best, a, i) => (a.citations > articles[best].citations ? i : best),
    0
  );

  /* ─── Generate scores for each article (parallel to `articles` by index) ─── */
  const articleScores = articles.map((article) => generateScores(article));

  /* ─── Radar chart data ───
   * One row per metric; each row spreads in a `Paper N` key per article so
   * recharts can draw one Radar series per paper over the shared axes. */
  const radarData = [
    {
      metric: 'Reliability',
      ...articles.reduce((acc, article, idx) => ({ ...acc, [`Paper ${idx + 1}`]: articleScores[idx].reliability }), {}),
    },
    {
      metric: 'Readability',
      ...articles.reduce((acc, article, idx) => ({ ...acc, [`Paper ${idx + 1}`]: articleScores[idx].readability }), {}),
    },
    {
      metric: 'Methodology',
      ...articles.reduce((acc, article, idx) => ({ ...acc, [`Paper ${idx + 1}`]: articleScores[idx].methodology }), {}),
    },
    {
      metric: 'Relevance',
      ...articles.reduce((acc, article, idx) => ({ ...acc, [`Paper ${idx + 1}`]: articleScores[idx].relevance }), {}),
    },
  ];

  const chartColors = ['#dc2626', '#2563eb', '#16a34a', '#f59e0b'];

  const handleExport = (format: 'pdf' | 'word') => {
    toast.success(`Exporting comparison as ${format.toUpperCase()}â€¦`, {
      description: 'Your file will be ready shortly.',
    });
  };

  return (
    <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm z-50 flex items-center justify-center p-2 md:p-6">
      <div className="bg-white w-full max-w-5xl max-h-[95vh] rounded-2xl shadow-2xl flex flex-col overflow-hidden border border-slate-200">

        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-slate-200 bg-white flex-shrink-0">
          <div className="flex items-center gap-3">
            <div>
              <ArticleIcon size="md" title="Comparison">
                <GitCompare className="w-5 h-5 text-current" />
              </ArticleIcon>
            </div>
            <div>
              <h2 className="font-bold text-slate-900 text-lg">Article Comparison</h2>
              <p className="text-xs text-slate-500">
                Comparing {articles.length} selected papers â€¢ AI-generated analysis
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            {/* Create Chat: broadcast a window event that ChatAnalyzer listens
                for, which spins up a new chat group from these articles, then
                close this modal. Decoupled via CustomEvent (no shared state). */}
            <button
              onClick={() => {
                const detail = { articleIds: articles.map(a => a.id), name: `Comparison: ${articles.map(a => a.title).slice(0,2).join(' / ')}` };
                window.dispatchEvent(new CustomEvent('create-chat-from-comparison', { detail }));
                onClose();
              }}
              className="px-3 py-1.5 bg-red-600 hover:bg-red-700 text-white rounded-lg text-xs font-bold mr-2"
            >
              Create Chat
            </button>
            {/* How AI got this */}
            <button
              onClick={() => setShowExplanation(!showExplanation)}
              className="hidden sm:flex items-center gap-1.5 px-3 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-600 rounded-lg text-xs font-bold transition-colors border border-slate-200"
            >
              <HelpCircle className="w-3.5 h-3.5" />
              How AI got this?
            </button>
            {/* Export dropdown */}
            <div className="relative group">
              <button className="flex items-center gap-1.5 px-3 py-1.5 bg-red-50 hover:bg-red-100 text-red-700 rounded-lg text-xs font-bold transition-colors border border-red-200">
                <Download className="w-3.5 h-3.5" />
                Export
              </button>
              <div className="absolute right-0 top-full mt-1 w-40 bg-white border border-slate-200 rounded-xl shadow-lg py-1 opacity-0 pointer-events-none group-hover:opacity-100 group-hover:pointer-events-auto transition-all z-30">
                <button
                  onClick={() => handleExport('pdf')}
                  className="w-full px-3 py-2 text-sm text-slate-700 hover:bg-red-50 hover:text-red-700 flex items-center gap-2 font-medium"
                >
                  <FileText className="w-4 h-4" /> Export to PDF
                </button>
                <button
                  onClick={() => handleExport('word')}
                  className="w-full px-3 py-2 text-sm text-slate-700 hover:bg-red-50 hover:text-red-700 flex items-center gap-2 font-medium"
                >
                  <FileText className="w-4 h-4" /> Export to Word
                </button>
              </div>
            </div>
            <button
              onClick={onClose}
              className="p-2 text-slate-400 hover:text-red-600 hover:bg-red-50 rounded-lg transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* AI Explanation banner */}
        {showExplanation && (
          <div className="mx-6 mt-4 bg-slate-100 dark:bg-slate-800 border border-slate-300 dark:border-slate-600 rounded-xl p-4 flex items-start gap-3 flex-shrink-0">
            <Info className="w-4 h-4 text-red-600 mt-0.5 flex-shrink-0" />
            <div>
              <p className="text-xs font-bold text-amber-800 mb-1">How AI generated this comparison</p>
              <p className="text-xs text-amber-700 leading-relaxed">{EXPLANATION}</p>
            </div>
            <button onClick={() => setShowExplanation(false)} className="text-amber-400 hover:text-amber-600 ml-auto flex-shrink-0">
              <X className="w-4 h-4" />
            </button>
          </div>
        )}

        {/* Content */}
        <div className="flex-1 flex flex-col min-w-0 min-h-0 relative overflow-hidden">

          {/* â•â•â• Visual Comparison Metrics â•â•â• */}
          <div className="px-6 pt-5 pb-4 space-y-5">

            {/* Radar Chart */}
            <div className="bg-white border border-slate-200 rounded-xl p-5">
              <h3 className="font-bold text-slate-800 text-sm mb-4 flex items-center gap-2">
                <TrendingUp className="w-4 h-4 text-red-600" />
                Multi-Dimensional Comparison
              </h3>
              <ResponsiveContainer width="100%" height={320}>
                <RadarChart data={radarData}>
                  <PolarGrid stroke="#e2e8f0" />
                  <PolarAngleAxis dataKey="metric" tick={{ fill: '#64748b', fontSize: 12, fontWeight: 600 }} />
                  <PolarRadiusAxis angle={90} domain={[0, 100]} tick={{ fill: '#94a3b8', fontSize: 10 }} />
                  {articles.map((_, idx) => (
                    <Radar
                      key={idx}
                      name={`Paper ${idx + 1}`}
                      dataKey={`Paper ${idx + 1}`}
                      stroke={chartColors[idx]}
                      fill={chartColors[idx]}
                      fillOpacity={0.2}
                      strokeWidth={2}
                    />
                  ))}
                  <Legend wrapperStyle={{ fontSize: '12px', fontWeight: 600 }} />
                </RadarChart>
              </ResponsiveContainer>
            </div>

            {/* Score Bars + Badges Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {articles.map((article, idx) => {
                const scores = articleScores[idx];
                const isBest = idx === bestMatchIdx;
                return (
                  <div
                    key={article.id}
                    className={`p-4 rounded-xl border-2 ${
                      isBest ? 'border-amber-400 bg-amber-50/30' : 'border-slate-200 bg-slate-50/50'
                    }`}
                  >
                    <div className="flex items-start justify-between mb-3">
                      <div className="flex-1 pr-2">
                        <h4 className="font-bold text-slate-900 text-sm leading-tight line-clamp-2 mb-1">
                          Paper {idx + 1}
                        </h4>
                        <p className="text-[11px] text-slate-500">
                          {article.authors[0]} et al. Â· {article.year}
                        </p>
                      </div>
                      {isBest && (
                        <div className="flex items-center gap-1 bg-amber-400 px-2 py-0.5 rounded-full">
                          <Star className="w-2.5 h-2.5 text-red-600 fill-amber-900" />
                          <span className="text-[10px] font-bold text-amber-900 uppercase">Best</span>
                        </div>
                      )}
                    </div>

                    {/* Numerical Badges */}
                    <div className="grid grid-cols-2 gap-2 mb-4">
                      <div className="flex items-center gap-2 px-3 py-2 bg-white border border-slate-200 rounded-lg">
                        <BookOpen className="w-3.5 h-3.5 text-red-600" />
                        <div>
                          <div className="text-[10px] font-bold text-slate-500 uppercase">Citations</div>
                          <div className="text-base font-bold text-slate-900">{scores.citations}</div>
                        </div>
                      </div>
                      <div className="flex items-center gap-2 px-3 py-2 bg-white border border-slate-200 rounded-lg">
                        <Award className="w-3.5 h-3.5 text-red-600" />
                        <div>
                          <div className="text-[10px] font-bold text-slate-500 uppercase">Impact</div>
                          <div className="text-base font-bold text-slate-900">{scores.impactFactor}</div>
                        </div>
                      </div>
                    </div>

                    {/* Score Progress Bars */}
                    <div className="space-y-2.5">
                      {[
                        { label: 'Reliability', value: scores.reliability },
                        { label: 'Readability', value: scores.readability },
                        { label: 'Methodology', value: scores.methodology },
                        { label: 'Relevance', value: scores.relevance },
                      ].map((item) => (
                        <div key={item.label}>
                          <div className="flex items-center justify-between mb-1">
                            <span className="text-[10px] font-bold text-slate-600 uppercase tracking-wide">
                              {item.label}
                            </span>
                            <span className="text-xs font-bold text-slate-700">{item.value}%</span>
                          </div>
                          <div className="h-2 bg-slate-200 rounded-full overflow-hidden">
                            <div
                              className="h-full rounded-full transition-all duration-500"
                              style={{
                                width: `${item.value}%`,
                                backgroundColor: chartColors[idx],
                              }}
                            />
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Article header cards (responsive flex row for screen) */}
          <div className="px-6 pt-5 pb-3">
            <div className="flex-1 flex flex-col min-w-0 min-h-0 relative overflow-hidden">
              <div className="flex items-start gap-4">
                <div className="w-[200px] flex-shrink-0" />
                <div className="flex-1 overflow-x-auto">
                  <div className="flex gap-4 min-w-max">
                    {articles.map((article, idx) => (
                      <div
                        key={article.id}
                        className={`bg-card rounded-2xl shadow-sm p-5 ${
                          idx === bestMatchIdx
                            ? 'border-amber-400 border-2 bg-amber-50'
                            : 'border border-border'
                        } w-72 flex-shrink-0`}
                      >
                        {idx === bestMatchIdx && (
                          <div className="flex items-center gap-1 mb-2">
                            <Star className="w-3.5 h-3.5 text-red-600 fill-amber-500" />
                            <span className="text-[10px] font-bold text-amber-700 uppercase tracking-wider">Best Match</span>
                          </div>
                        )}
                        <h3 className="font-bold text-slate-900 text-sm leading-tight line-clamp-3 mb-2">
                          {article.title}
                        </h3>
                        <p className="text-[11px] text-slate-500 font-medium">
                          {article.authors[0]} et al. Â· {article.year}
                        </p>
                        <div className="mt-2 flex items-center gap-1">
                          <span className="text-[10px] font-bold text-slate-400 uppercase">Citations:</span>
                          <span className="text-xs font-bold text-red-600">{article.citations}</span>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Comparison table */}
          <div className="px-6 pb-4">
            <div className="bg-white border border-slate-200 rounded-xl overflow-hidden">
              <div className="overflow-x-auto">
                <table className="w-full min-w-[600px]">
                  <tbody>
                    {comparisonCategories.map((cat, idx) => (
                      <tr key={cat.key} className={idx % 2 === 0 ? 'bg-white' : 'bg-slate-50/80'}>
                        <td className="px-4 py-3.5 font-bold text-slate-700 text-sm border-r border-slate-200 w-[200px] align-top whitespace-nowrap">
                          {cat.label}
                        </td>
                        {articles.map((article) => (
                          <td key={article.id} className="px-4 py-3.5 align-top border-r border-slate-100 last:border-r-0">
                            {renderCell(article, cat.key)}
                          </td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          {/* AI Insights */}
          <div className="px-6 pb-6">
            <h3 className="font-bold text-slate-800 text-sm mb-3 flex items-center gap-2">
              <GitCompare className="w-4 h-4 text-red-600" />
              AI Insights from Comparison
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {aiInsights.map((insight, idx) => (
                <div
                  key={idx}
                  className="bg-white border border-slate-200 rounded-xl overflow-hidden cursor-pointer hover:border-red-300 hover:shadow-sm transition-all"
                  onClick={() => setActiveInsight(activeInsight === idx ? null : idx)}
                >
                  <div className="flex items-center justify-between px-4 py-3">
                    <span className="font-bold text-slate-800 text-sm">{insight.label}</span>
                    {activeInsight === idx
                      ? <ChevronUp className="w-4 h-4 text-red-600" />
                      : <ChevronDown className="w-4 h-4 text-red-600" />
                    }
                  </div>
                  {activeInsight === idx && (
                    <div className="px-4 pb-4 border-t border-slate-100">
                      <p className="text-sm text-slate-600 leading-relaxed pt-3">{insight.text}</p>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
