/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "umpaxvkbhlgwdabjrwss"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtcGF4dmtiaGxnd2RhYmpyd3NzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzczNDg1OTUsImV4cCI6MjA5MjkyNDU5NX0.7oM66xiv_4-IrZ-ntIMJqMYw4GKbrhGIpHZOgUkhYG0"